config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :conversations
  end
  resources :users do
    resource :profile
  end
  resources :contacts
  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
    belongs_to :user
    has_many :messages
end

app/models/inbox.rb
class Inbox < ActiveRecord::Base
    belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
    belongs_to :inbox
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :users
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :thread
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
    
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/thread.rb
class Thread < ActiveRecord::Base
    belongs_to :user
    has_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  has_many :conversations
  has_many :threads
  attr_accessor :stripe_card_token
  
  def save_with_payment
    if valid? #check validations on page
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end

    def create
        @contact = Contact.new(contact_params)
        
        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
            
            ContactMailer.contact_email(name, email, body).deliver #send out email when a new contact is saved
            flash[:success] = 'Message sent.'
            redirect_to new_contact_path
        else
            flash[:danger] = 'Error occured, message has not been sent.'
            redirect_to new_contact_path
        end
    end
    
    private
        def contact_params
            params.require(:contact).permit(:name, :email, :comments) 
        end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    def new
       # inbox where user has messages from other users
       @user = User.find(params[:user_id] )
       @sendTo = params[:sendTo]
       @receiver = User.find(@sendTo).profile.contact_email
    end
end

app/controllers/inboxes_controller.rb
class InboxesController < ApplicationController
    def new
       # inbox where user has messages from other users
       @user = User.find(params[:user_id] )
       @inbox = @user.build_inbox
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @basic_plan = Plan.find(1)
        @pro_plan = Plan.find(2)
    end
    def about
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user! #before_action is a rails command, :authenticate_user is a devise function
    before_action :only_current_user
    #before_action :authenticate_user!, only: [:new, :edit] <--- this would only do the before action for those 2 pages
    def new
       # form where a user can fill out their own profile.
       @user = User.find( params[:user_id] )
       @profile = Profile.new
    end
    
    def create
       @user = User.find( params[:user_id] ) 
       @profile = @user.build_profile(profile_params)
       if @profile.save
          flash[:success] = "Profile Updated!"
          redirect_to user_path( params[:user_id] )
       else
          render action: :new   
       end
    end
    
    def edit
        @user = User.find( params[:user_id] ) 
        @profile = @user.profile
    end 
    
    def update
        @user = User.find( params[:user_id] )
        @profile = @user.profile
        if @profile.update_attributes(profile_params)
            flash[:success] = "Profile Updated!"
            redirect_to user_path( params[:user_id] ) 
        else
            flash[:danger] = "Profile update failed!"
            render action: :edit
        end
    end
    
    #whitelist what you need the user to submit
    private
        def profile_params
           params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description) 
        end
        
        def only_current_user
           @user = User.find( params[:user_id] ) 
           redirect_to(root_url) unless @user == current_user
        end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_filter :select_plan, only: :new
    def create
        super do |resource|
            if params[:plan]
                resource.plan_id = params[:plan]
                if resource.plan_id == 2
                    resource.save_with_payment
                else
                    resource.save
                end
            end
        end
    end
    
    private
        def select_plan
          unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
                flash[:notice] = "Please select a membership plan to sign up."
                redirect_to root_url
          end
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!
   
   def index
      @users = User.all
      @user = ""      
   end
   
   def show
      @user = User.find(params[:id] )
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper

    def job_title_icon
       if @user.profile.job_title == "Developer"
        "<i class='fa fa-code'></i>".html_safe
       elsif @user.profile.job_title == "Entrepreneur"
        "<i class='fa fa-lightbulb-o'></i>".html_safe
       elsif @user.profile.job_title == "Investor"
        "<i class='fa fa-dollar'></i>".html_safe
       end 
    end
end

app/helpers/users_helper.rb
module UsersHelper

    def job_title_icon
       if @user.profile.job_title == "Developer"
        "<i class='fa fa-code'></i>".html_safe
       elsif @user.profile.job_title == "Entrepreneur"
        "<i class='fa fa-lightbulb-o'></i>".html_safe
       elsif @user.profile.job_title == "Investor"
        "<i class='fa fa-dollar'></i>".html_safe
       end 
    end
end

app/views/contacts/new.html.erb
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h1 class="text-center">Contact Us</h1>
        <p  class="text-center">Reach out if you have any questions or comments.</p>
        <div class="well">
            <%= form_for @contact do |f| %>
                <div class="form-group">
                    <%= f.label :name%>
                    <%= f.text_field :name, class: 'form-control'%>
                </div>
                <div class="form-group">
                    <%= f.label :email%>
                    <%= f.email_field :email, class: 'form-control'%>
                </div>
                
                <div class="form-group">
                    <%= f.label :comments%>
                    <%= f.text_area :comments, class: 'form-control'%>
                </div>
                <%= f.submit 'Submit', class: 'btn <btn-default>'%>
            <% end %>
        </div>
    </div>
</div>

app/views/conversations/new.html.erb
Reciever: <%= @receiver %> <br>
Sender: <%= current_user.profile.contact_email %>

app/views/inbox/new.html.erb
User Inbox

app/views/messages/new.html.erb
You clicked on the user with an ID of <% @user %> 

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, html: { multipart: true } do |f| %>
    <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :avatar %>
        <%= f.file_field :avatar, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :job_title %>
        <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :contact_email %>
        <%= f.text_field :contact_email, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="form-group">
        
    </div>
    <div class="form-group">
        <%= f.submit "Update Profile", class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Edit Your Profile</h1>
        <p class="text-center">Be a part of the Dev Match community and fill out your profile!</p>
        <div class="well">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Create Your Profile</h1>
        <p class="text-center">Be a part of the Dev Match community and fill out your profile!</p>
        <div class="well">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1  class="text-center">Dev Match Community</h1>
        <p  class="text-center">Welcome to the Dev Match community.  Users must fill out a profile in order to be visible in the community.</p>
            <ul class="list-unstyled">
                <% @users.each do |user| %>
                    <% if user.profile %>
                        <% @user = user %>
                        <li>
                            <%= link_to user do %>
                                <div class="well row <%= cycle('white-bg', '') %>">
                                    <div class="col-sm-4 text-center">
                                        <% if user.profile.avatar %>
                                            <%= image_tag user.profile.avatar.url(:thumb), class: 'user-index-avatar' %>
                                        <% end %>
        
                                    </div>
                                    <div>
                                        <h2><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
                                        <p>
                                            <%= job_title_icon %> <%= user.profile.job_title %>
                                            <% if user.plan_id == 2 %>
                                                <span class="label label-danger">PRO</span>
                                            <% end %>
                                        </p>
                                    </div>
                                </div>
                            <% end %>
                        </li>
                    <% end %>
                <% end %>
            </ul>
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-6">
        <%= image_tag @user.profile.avatar.url, class: 'user-show-avatar'%><br/>
    </div>
    <div class="col-md-6">
        <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
        <h3><span class="job-title-icon"><%= job_title_icon %></span> <%= @user.profile.job_title %></h3>
        <div class="well profile-description">
            <h3>Description</h3>
            <%= @user.profile.description %>
        </div>
        
        <% if current_user.plan_id == 2 %>
            <div class="well contact-info">
                <h3>Contact Info</h3>
                <%= @user.profile.phone_number %><br/>
                <%= @user.profile.contact_email %><br/>
                glyphicon glyphicon-envelope
            </div>
        <% end %>
        <div>
            <% if current_user != @user %>
                <h3><%= link_to content_tag(:i, " Sent me a message", :class => "fa fa-envelope-o email-link"), new_user_conversations_path(current_user, sendTo: @user.id) %></h3>
            <% end %>
            <h6><%= @user.id %> </h6>
        </div>
    </div>
</div>